//! Integration tests for prunr-core.
//!
//! Prerequisites:
//!   1. Download test images: see tests/test_images/README.md
//!   2. Generate reference masks: python scripts/generate_references.py
//!   3. Run: cargo test -p prunr-core --features dev-models
//!
//! The reference test (test_rembg_reference) is the CORE-05 hard gate.
//! It must pass before any CLI or GUI work proceeds.

use prunr_core::{
    CoreError, InferenceEngine, ModelKind, OrtEngine, ProgressStage,
    LARGE_IMAGE_LIMIT, DOWNSCALE_TARGET,
    process_image, batch_process,
    check_large_image, downscale_image,
};
use std::sync::Arc;
use std::sync::atomic::AtomicBool;
use image::{DynamicImage, RgbaImage};
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    // Integration tests run from workspace root with `cargo test -p prunr-core`
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()   // crates/
        .unwrap()
        .parent()   // workspace root
        .unwrap()
        .to_path_buf()
}

fn test_images_dir() -> PathBuf {
    repo_root().join("tests").join("test_images")
}

fn references_dir() -> PathBuf {
    repo_root().join("tests").join("references")
}

/// Load reference alpha mask from tests/references/{stem}_u2net_mask.png
/// Returns a GrayImage (single channel).
fn load_reference_mask(stem: &str) -> Option<image::GrayImage> {
    let mask_path = references_dir().join(format!("{stem}_u2net_mask.png"));
    if !mask_path.exists() {
        eprintln!("Reference mask not found: {} — skipping", mask_path.display());
        return None;
    }
    Some(image::open(&mask_path)
        .expect("Failed to open reference mask")
        .to_luma8())
}

/// Calculate pixel match percentage between two alpha channels.
/// A pixel matches if |prunr_alpha - reference_alpha| <= tolerance.
fn pixel_match_percent(our_rgba: &RgbaImage, reference_mask: &image::GrayImage, tolerance: u8) -> f64 {
    assert_eq!(our_rgba.width(), reference_mask.width(),
        "Width mismatch: {}x{} vs {}x{}", our_rgba.width(), our_rgba.height(),
        reference_mask.width(), reference_mask.height());
    assert_eq!(our_rgba.height(), reference_mask.height(),
        "Height mismatch");

    let total = (our_rgba.width() * our_rgba.height()) as f64;
    let mut matched = 0u64;

    for y in 0..our_rgba.height() {
        for x in 0..our_rgba.width() {
            let our_alpha = our_rgba.get_pixel(x, y)[3];
            let ref_alpha = reference_mask.get_pixel(x, y)[0];
            if (our_alpha as i32 - ref_alpha as i32).unsigned_abs() as u8 <= tolerance {
                matched += 1;
            }
        }
    }

    (matched as f64 / total) * 100.0
}

// ============================================================
// CORE-05: Pixel-accuracy reference test (HARD GATE)
// ============================================================

/// CORE-05 hard gate: Prunr output must match rembg Python output at 95% pixel accuracy.
///
/// This test runs process_image() on three test images using u2net and compares the
/// resulting alpha channel against masks generated by scripts/generate_references.py.
///
/// PREREQUISITE: Run `python scripts/generate_references.py` before running this test.
/// See tests/test_images/README.md for image download instructions.
#[test]
fn test_rembg_reference() {
    // U2Net is OnDemand — skip unless installed.
    if !prunr_models::is_available(prunr_models::ModelId::U2net) {
        eprintln!("Skipping rembg reference: U2Net not installed in user data dir");
        return;
    }
    let engine = OrtEngine::new(ModelKind::U2net, 1)
        .expect("Failed to create OrtEngine — U2Net reported available but session creation failed");

    let test_cases = ["car-1", "car-2", "car-3"];
    let tolerance: u8 = 5;   // |our_alpha - ref_alpha| <= 5 counts as match
    let required_pct: f64 = 95.0;

    for stem in &test_cases {
        let image_path = test_images_dir().join(format!("{stem}.jpg"));
        if !image_path.exists() {
            eprintln!("Skipping reference test for {stem}: image not found at {}", image_path.display());
            continue;
        }

        let img_bytes = std::fs::read(&image_path)
            .expect("Failed to read test image");

        let result = process_image(&img_bytes, &engine, None::<fn(ProgressStage, f32)>, None::<Arc<AtomicBool>>)
            .unwrap_or_else(|e| panic!("process_image failed for {stem}: {e}"));

        let our_rgba = result.rgba_image;

        let Some(ref_mask) = load_reference_mask(stem) else {
            continue;
        };

        // Reference mask is at full-size (rembg returns full-size output matching the input).
        // If reference mask dimensions differ from our output, resize reference mask to match
        // (using nearest neighbor for pixel-accurate comparison).
        let ref_mask = if ref_mask.width() != our_rgba.width() || ref_mask.height() != our_rgba.height() {
            image::imageops::resize(
                &ref_mask,
                our_rgba.width(),
                our_rgba.height(),
                image::imageops::FilterType::Nearest,
            )
        } else {
            ref_mask
        };

        let pct = pixel_match_percent(&our_rgba, &ref_mask, tolerance);

        assert!(
            pct >= required_pct,
            "CORE-05 FAILED for {stem}: {pct:.1}% match (required {required_pct}%)\n\
             Check preprocessing pipeline matches rembg exactly:\n\
             - Resize: Lanczos3 (NOT bilinear)\n\
             - Normalization: max(max_pixel, 1e-6) (NOT 255.0)\n\
             - Postprocessing: min-max only (NOT sigmoid, NOT threshold)"
        );

        println!("CORE-05 [{stem}]: {pct:.1}% pixel match (tolerance=\u{b1}{tolerance}, required={required_pct}%) PASS");
    }
}

// ============================================================
// CORE-01: Single image processing
// ============================================================

#[test]
fn test_process_image_produces_valid_rgba_png() {
    let engine = OrtEngine::new(ModelKind::Silueta, 1)
        .expect("Failed to create OrtEngine");

    let image_path = test_images_dir().join("car-1.jpg");
    if !image_path.exists() {
        eprintln!("Skipping: car-1.jpg not found — see tests/test_images/README.md");
        return;
    }

    let img_bytes = std::fs::read(&image_path).unwrap();
    let result = process_image(&img_bytes, &engine, None::<fn(ProgressStage, f32)>, None::<Arc<AtomicBool>>)
        .expect("process_image should succeed");

    // Verify output has transparency (not all-opaque)
    let has_transparency = result.rgba_image.pixels().any(|p| p[3] < 255);
    assert!(has_transparency, "Background removal must produce at least some transparent pixels");
}

// ============================================================
// CORE-02: Model selection
// ============================================================

#[test]
fn test_model_selection_silueta_and_u2net() {
    // Silueta is bundled — must always load.
    let _silueta = OrtEngine::new(ModelKind::Silueta, 1)
        .expect("Silueta model should load");
    // U2Net is OnDemand — only load when present.
    if prunr_models::is_available(prunr_models::ModelId::U2net) {
        let _u2net = OrtEngine::new(ModelKind::U2net, 1)
            .expect("U2net reported available but session creation failed");
    }
}

// ============================================================
// CORE-03: Active provider query
// ============================================================

#[test]
fn test_active_provider_queryable() {
    let engine = OrtEngine::new(ModelKind::Silueta, 1)
        .expect("OrtEngine::new should succeed");
    let provider = engine.active_provider();
    assert!(!provider.is_empty(), "active_provider() must return a non-empty string");
    println!("Active execution provider: {provider}");
}

// ============================================================
// CORE-04: Progress callback
// ============================================================

#[test]
fn test_progress_callback_all_stages() {
    use std::sync::{Arc, Mutex};

    let engine = OrtEngine::new(ModelKind::Silueta, 1)
        .expect("OrtEngine::new should succeed");

    let image_path = test_images_dir().join("car-1.jpg");
    if !image_path.exists() {
        eprintln!("Skipping: car-1.jpg not found");
        return;
    }

    let img_bytes = std::fs::read(&image_path).unwrap();

    let stages: Arc<Mutex<Vec<ProgressStage>>> = Arc::new(Mutex::new(Vec::new()));
    let stages_clone = stages.clone();

    let _ = process_image(&img_bytes, &engine, Some(move |stage, pct| {
        stages_clone.lock().unwrap().push(stage);
        assert!(pct >= 0.0 && pct <= 1.0, "Progress pct must be in [0.0, 1.0], got {pct}");
    }), None::<Arc<AtomicBool>>);

    let recorded = stages.lock().unwrap();
    assert!(recorded.len() >= 5, "Expected at least 5 progress stages, got {}", recorded.len());

    // Verify Infer stage is present (most important for UI feedback)
    assert!(
        recorded.iter().any(|s| matches!(s, ProgressStage::Infer)),
        "ProgressStage::Infer must be reported"
    );
}

// ============================================================
// LOAD-03: Format support
// ============================================================

#[test]
fn test_format_support_png_jpeg_webp_bmp() {
    use image::{DynamicImage, RgbImage, Rgb};
    use std::io::Cursor;

    let test_img = DynamicImage::ImageRgb8(RgbImage::from_pixel(32, 32, Rgb([100, 150, 200])));
    let engine = OrtEngine::new(ModelKind::Silueta, 1).expect("Engine");

    // Test each format by encoding to bytes then calling process_image
    let formats = [
        ("PNG",  image::ImageFormat::Png),
        ("JPEG", image::ImageFormat::Jpeg),
        ("BMP",  image::ImageFormat::Bmp),
    ];

    for (name, fmt) in &formats {
        let mut buf = Vec::new();
        test_img.write_to(&mut Cursor::new(&mut buf), *fmt).unwrap();

        let result = process_image(&buf, &engine, None::<fn(ProgressStage, f32)>, None::<Arc<AtomicBool>>);
        assert!(result.is_ok(), "Format {name} should be supported: {:?}", result.err());
    }

    // WebP: generate via image crate (requires webp feature)
    // image 0.25 supports WebP encode; create a small WebP from RGB data
    {
        let mut buf = Vec::new();
        test_img.write_to(&mut Cursor::new(&mut buf), image::ImageFormat::WebP)
            .expect("WebP encode should work with image 0.25 webp feature");
        let result = process_image(&buf, &engine, None::<fn(ProgressStage, f32)>, None::<Arc<AtomicBool>>);
        assert!(result.is_ok(), "WebP format should be supported: {:?}", result.err());
    }
}

// ============================================================
// LOAD-04: Large image handling
// ============================================================

#[test]
fn test_large_image_warning() {
    // check_large_image returns LargeImage error for > 8000px images
    let large = DynamicImage::ImageRgb8(image::RgbImage::new(9000, 100));
    let err = check_large_image(&large);
    assert!(err.is_some(), "Expected LargeImage warning for 9000px image");
    match err.unwrap() {
        CoreError::LargeImage { width, height: _, limit } => {
            assert_eq!(width, 9000);
            assert_eq!(limit, LARGE_IMAGE_LIMIT);
        }
        other => panic!("Expected LargeImage, got {:?}", other),
    }
}

#[test]
fn test_downscale_image_preserves_aspect_ratio() {
    // 8000x4000 → max_dim 4096 → 4096x2048 (aspect preserved)
    let img = DynamicImage::ImageRgb8(image::RgbImage::new(8000, 4000));
    let scaled = downscale_image(img, DOWNSCALE_TARGET);

    assert!(
        scaled.width().max(scaled.height()) <= DOWNSCALE_TARGET,
        "Downscaled max dimension {} exceeds {}",
        scaled.width().max(scaled.height()), DOWNSCALE_TARGET
    );

    let aspect_original = 8000.0_f64 / 4000.0;
    let aspect_scaled = scaled.width() as f64 / scaled.height() as f64;
    assert!(
        (aspect_original - aspect_scaled).abs() < 0.02,
        "Aspect ratio changed too much: {aspect_original:.3} → {aspect_scaled:.3}"
    );
}

// ============================================================
// CORE-05 + CORE-01: Batch API
// ============================================================

#[test]
fn test_batch_process_multiple_images() {
    let image_path_1 = test_images_dir().join("car-1.jpg");
    let image_path_2 = test_images_dir().join("car-2.jpg");

    if !image_path_1.exists() || !image_path_2.exists() {
        eprintln!("Skipping batch test: test images not found");
        return;
    }

    let img1 = std::fs::read(&image_path_1).unwrap();
    let img2 = std::fs::read(&image_path_2).unwrap();
    let images: Vec<&[u8]> = vec![img1.as_slice(), img2.as_slice()];

    let results = batch_process(
        &images,
        ModelKind::Silueta,
        1,
        None::<fn(usize, ProgressStage, f32)>,
    );

    assert_eq!(results.len(), 2, "batch_process must return one result per input");
    for (i, r) in results.iter().enumerate() {
        assert!(r.is_ok(), "Batch result {} failed: {:?}", i, r);
    }
}

/// End-to-end smoke test for the LaMa inpaint pipeline.
///
/// Runs `process_inpaint` over a real image with a small synthetic mask
/// patch in the centre. We don't have a deterministic golden output (LaMa
/// is data-hungry to pin pixel-exact), so the assertions validate the
/// I/O contract rather than the pixel values:
///
/// - Output dimensions match the input
/// - Pixels OUTSIDE the mask are byte-identical to the source (the
///   `decode_tile` source-passthrough invariant)
/// - At least one pixel INSIDE the mask differs from the source (the
///   model actually painted something — catches a wiring regression
///   that returned the source unchanged)
///
/// Skipped when the LaMa model isn't on disk.
#[test]
#[cfg(feature = "dev-models")]
fn test_inpaint_smoke() {
    let image_path = test_images_dir().join("car-1.jpg");
    if !image_path.exists() {
        eprintln!("Skipping inpaint smoke test: car-1.jpg not found");
        return;
    }
    // LaMa is OnDemand — skip unless the user has it in their data dir.
    if !prunr_models::is_available(prunr_models::ModelId::LaMaFp32) {
        eprintln!("Skipping inpaint smoke test: LaMa not installed in user data dir");
        return;
    }

    let dyn_img = image::open(&image_path).expect("Failed to open car-1.jpg");
    let img = dyn_img.into_rgba8();
    let (w, h) = img.dimensions();

    // Synthesise a 32×32 mask patch in the centre of the image.
    let mut mask = image::GrayImage::new(w, h);
    let cx = w / 2;
    let cy = h / 2;
    let r = 16u32;
    for y in cy.saturating_sub(r)..(cy + r).min(h) {
        for x in cx.saturating_sub(r)..(cx + r).min(w) {
            mask.put_pixel(x, y, image::Luma([255]));
        }
    }

    let result = prunr_core::inpaint::process_inpaint(&img, &mask, prunr_models::ModelId::LaMaFp32)
        .expect("process_inpaint failed");
    assert_eq!(result.dimensions(), img.dimensions());

    // Outside the mask: byte-identical to source.
    for y in 0..h {
        for x in 0..w {
            if mask.get_pixel(x, y).0[0] == 0 {
                assert_eq!(
                    result.get_pixel(x, y), img.get_pixel(x, y),
                    "unmasked pixel ({x}, {y}) was modified — decode_tile passthrough broken",
                );
            }
        }
    }

    // Inside the mask: at least one pixel must differ from the source.
    let mut any_changed = false;
    for y in cy.saturating_sub(r)..(cy + r).min(h) {
        for x in cx.saturating_sub(r)..(cx + r).min(w) {
            if mask.get_pixel(x, y).0[0] != 0
                && result.get_pixel(x, y) != img.get_pixel(x, y) {
                any_changed = true;
                break;
            }
        }
        if any_changed { break; }
    }
    assert!(any_changed, "no masked pixel was changed — LaMa returned source unchanged");
}
