// Production: models are embedded as pre-compressed zstd blobs and decompressed at runtime.
// Development: --features dev-models loads from the filesystem so model changes
// do not trigger recompilation of the prunr-models crate.
//
// IMPORTANT: This crate has NO dependencies on other workspace crates.
// The dependency arrow is prunr-app -> prunr-core -> prunr-models (never in reverse).

use std::sync::OnceLock;

/// Embedded pre-compressed model data (plain include_bytes — no compile-time decompression).
#[cfg(not(feature = "dev-models"))]
static SILUETA_ZST: &[u8] = include_bytes!("../../../models/silueta.onnx.zst");
#[cfg(not(feature = "dev-models"))]
static U2NET_ZST: &[u8] = include_bytes!("../../../models/u2net.onnx.zst");
#[cfg(not(feature = "dev-models"))]
static BIREFNET_LITE_ZST: &[u8] = include_bytes!("../../../models/birefnet_lite.onnx.zst");
#[cfg(not(feature = "dev-models"))]
static DEXINED_ZST: &[u8] = include_bytes!("../../../models/dexined.onnx.zst");

/// Cached decompressed model bytes — decompressed once, reused across engine creations.
#[cfg(not(feature = "dev-models"))]
static SILUETA_CACHE: OnceLock<Vec<u8>> = OnceLock::new();
#[cfg(not(feature = "dev-models"))]
static U2NET_CACHE: OnceLock<Vec<u8>> = OnceLock::new();
#[cfg(not(feature = "dev-models"))]
static BIREFNET_LITE_CACHE: OnceLock<Vec<u8>> = OnceLock::new();
#[cfg(not(feature = "dev-models"))]
static DEXINED_CACHE: OnceLock<Vec<u8>> = OnceLock::new();

#[cfg(not(feature = "dev-models"))]
pub fn silueta_bytes() -> Vec<u8> {
    SILUETA_CACHE.get_or_init(|| {
        zstd::bulk::decompress(SILUETA_ZST, 50 * 1024 * 1024)
            .expect("failed to decompress embedded silueta model")
    }).clone()
}

#[cfg(not(feature = "dev-models"))]
pub fn u2net_bytes() -> Vec<u8> {
    U2NET_CACHE.get_or_init(|| {
        zstd::bulk::decompress(U2NET_ZST, 200 * 1024 * 1024)
            .expect("failed to decompress embedded u2net model")
    }).clone()
}

#[cfg(not(feature = "dev-models"))]
pub fn birefnet_lite_bytes() -> Vec<u8> {
    BIREFNET_LITE_CACHE.get_or_init(|| {
        zstd::bulk::decompress(BIREFNET_LITE_ZST, 250 * 1024 * 1024)
            .expect("failed to decompress embedded birefnet-lite model")
    }).clone()
}

#[cfg(not(feature = "dev-models"))]
pub fn dexined_bytes() -> Vec<u8> {
    DEXINED_CACHE.get_or_init(|| {
        zstd::bulk::decompress(DEXINED_ZST, 150 * 1024 * 1024)
            .expect("failed to decompress embedded dexined model")
    }).clone()
}

#[cfg(feature = "dev-models")]
pub fn silueta_bytes() -> Vec<u8> {
    std::fs::read(
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../models/silueta.onnx"),
    )
    .expect("models/silueta.onnx not found — run `cargo xtask fetch-models`")
}

#[cfg(feature = "dev-models")]
pub fn u2net_bytes() -> Vec<u8> {
    std::fs::read(
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../models/u2net.onnx"),
    )
    .expect("models/u2net.onnx not found — run `cargo xtask fetch-models`")
}

#[cfg(feature = "dev-models")]
pub fn birefnet_lite_bytes() -> Vec<u8> {
    std::fs::read(
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../models/birefnet_lite.onnx"),
    )
    .expect("models/birefnet_lite.onnx not found — run `cargo xtask fetch-models`")
}

#[cfg(feature = "dev-models")]
pub fn dexined_bytes() -> Vec<u8> {
    std::fs::read(
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../models/dexined.onnx"),
    )
    .expect("models/dexined.onnx not found — run `cargo xtask fetch-models`")
}

// ── Optimized model variants (FP16 for GPU, INT8 for CPU) ───────────────────
// Generated by: python scripts/convert_models.py
// These return None when the variant hasn't been generated yet, triggering
// FP32 fallback in the engine.

/// Model identifier passed from prunr-core (avoids circular dependency on ModelKind).
#[derive(Debug, Clone, Copy)]
pub enum Model { Silueta, U2net, BiRefNetLite }

/// Load FP16 model variant (for GPU inference). Returns None if not available.
pub fn model_fp16_bytes(model: Model) -> Option<Vec<u8>> {
    load_variant(model, "fp16")
}

/// Load INT8 model variant (for CPU inference). Returns None if not available.
pub fn model_int8_bytes(model: Model) -> Option<Vec<u8>> {
    load_variant(model, "int8")
}

fn load_variant(model: Model, suffix: &str) -> Option<Vec<u8>> {
    let name = match model {
        Model::Silueta => "silueta",
        Model::U2net => "u2net",
        Model::BiRefNetLite => "birefnet_lite",
    };
    let filename = format!("{name}_{suffix}.onnx");

    // Dev builds: try source tree relative to CARGO_MANIFEST_DIR
    #[cfg(debug_assertions)]
    {
        let dev_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../models")
            .join(&filename);
        if let Ok(bytes) = std::fs::read(&dev_path) {
            return Some(bytes);
        }
    }

    // Release builds: try next to the running binary
    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            if let Ok(bytes) = std::fs::read(dir.join("models").join(&filename)) {
                return Some(bytes);
            }
        }
    }

    None
}

#[cfg(test)]
mod tests {
    // Tests run with --features dev-models to avoid embedding 174MB during testing.
    // Compile-time test: verifies the public API surface compiles correctly.

    #[test]
    fn test_model_api_compiles() {
        // When dev-models feature is active, these functions must exist and be callable.
        // Actual file I/O is NOT tested here (models may not be downloaded yet).
        // This test simply verifies the module compiles and the public API is accessible.
        #[cfg(feature = "dev-models")]
        {
            // Verify function signatures are correct (fn() -> Vec<u8>).
            let _: fn() -> Vec<u8> = super::silueta_bytes;
            let _: fn() -> Vec<u8> = super::u2net_bytes;
            let _: fn() -> Vec<u8> = super::birefnet_lite_bytes;
        }
        #[cfg(not(feature = "dev-models"))]
        {
            let _: fn() -> Vec<u8> = super::silueta_bytes;
            let _: fn() -> Vec<u8> = super::u2net_bytes;
            let _: fn() -> Vec<u8> = super::birefnet_lite_bytes;
        }
    }
}
